### ISSUE TITLE
Drop remote support?

### ISSUE THREAD

**Issue by SamVerschueren** [SamVerschueren/gh-lint#1]
Should we drop support for GitHub repositories and only lint local projects? Don't think lots of people will use that feature.

**Comment by sindresorhus** [comment]
👍 I don't I would ever use it for a remote repo and removing support for simplify a lot of things.

**Comment by SamVerschueren** [comment]
Closed in https://github.com/SamVerschueren/gh-lint/commit/0b7c41e13ae616a3c7ce15919730d679bd411121
